name: bowlingball-storybook-deploy
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }} event"
      - run: echo "Running on ${{ runner.os }}"
      - run: echo "Branch ${{ github.ref }}, Repo: ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "Clone complete"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          echo "hello"
      - run: echo "Status ${{ job.status }}"
